// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SmartFactoryCMMS.Api.Data;

#nullable disable

namespace SmartFactoryCMMS.Api.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260824122559_AddRefreshTokensTable")]
    partial class AddRefreshTokensTable
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.25")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("SmartFactoryCMMS.Api.Models.AlertThreshold", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("CriticalValue")
                        .HasColumnType("decimal(18,2)");

                    b.Property<Guid>("MachineId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("MetricType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("WarningValue")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("MachineId");

                    b.ToTable("AlertThresholds");
                });

            modelBuilder.Entity("SmartFactoryCMMS.Api.Models.FactoryHall", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("FactoryHalls");
                });

            modelBuilder.Entity("SmartFactoryCMMS.Api.Models.Incident", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("MachineId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Severity")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("TriggeredAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("MachineId");

                    b.ToTable("Incidents");
                });

            modelBuilder.Entity("SmartFactoryCMMS.Api.Models.Machine", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("CycleTimeSeconds")
                        .HasColumnType("float");

                    b.Property<Guid>("FactoryHallId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Icon")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("InstallationDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("LastStatusChangedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("OrderInLine")
                        .HasColumnType("int");

                    b.Property<Guid?>("ProductionLineId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("SerialNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("StaticProperties")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("TotalOperatingHours")
                        .HasColumnType("float");

                    b.Property<int>("TotalProduced")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("FactoryHallId");

                    b.HasIndex("ProductionLineId");

                    b.ToTable("Machines");
                });

            modelBuilder.Entity("SmartFactoryCMMS.Api.Models.MachinePrediction", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CalculatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("HealthScore")
                        .HasColumnType("int");

                    b.Property<Guid>("MachineId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("PredictedFailureComponent")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("RemainingUsefulLifeHours")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("MachineId");

                    b.ToTable("MachinePredictions");
                });

            modelBuilder.Entity("SmartFactoryCMMS.Api.Models.Product", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("SKUNumber")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.ToTable("Products");
                });

            modelBuilder.Entity("SmartFactoryCMMS.Api.Models.ProductionLine", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("CurrentProductId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("FactoryHallId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("LastStatusChangedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int?>("OrderInHall")
                        .HasColumnType("int");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("CurrentProductId");

                    b.HasIndex("FactoryHallId");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("ProductionLines");
                });

            modelBuilder.Entity("SmartFactoryCMMS.Api.Models.ProductionLog", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("ActiveOperatingSeconds")
                        .HasColumnType("int");

                    b.Property<decimal?>("AverageCycleTimeSeconds")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("DefectiveParts")
                        .HasColumnType("int");

                    b.Property<int>("GoodParts")
                        .HasColumnType("int");

                    b.Property<decimal?>("IdealCycleTimeSeconds")
                        .HasColumnType("decimal(18,2)");

                    b.Property<Guid>("MachineId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ShiftId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("MachineId");

                    b.HasIndex("ShiftId");

                    b.ToTable("ProductionLogs");
                });

            modelBuilder.Entity("SmartFactoryCMMS.Api.Models.RefreshToken", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedByIp")
                        .HasMaxLength(45)
                        .HasColumnType("nvarchar(45)");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("ReplacedByTokenId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("RevokedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("TokenHash")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("UserAgent")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("TokenHash");

                    b.HasIndex("UserId");

                    b.ToTable("RefreshTokens");
                });

            modelBuilder.Entity("SmartFactoryCMMS.Api.Models.SystemSettings", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("EnableEmailAlerts")
                        .HasColumnType("bit");

                    b.Property<decimal>("PeakPowerLimitMw")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("RawTelemetryRetentionDays")
                        .HasColumnType("int");

                    b.Property<string>("SiteName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SlackWebhookUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Timezone")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("SystemSettings");
                });

            modelBuilder.Entity("SmartFactoryCMMS.Api.Models.TelemetryRead", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("AdditionalMetrics")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("MachineId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int?>("NetworkLatencyMs")
                        .HasColumnType("int");

                    b.Property<decimal?>("PowerLoadKw")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("Temperature")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("datetime2");

                    b.Property<decimal?>("Vibration")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("MachineId");

                    b.ToTable("TelemetryRead");
                });

            modelBuilder.Entity("SmartFactoryCMMS.Api.Models.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<Guid?>("FactoryHallId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("FactoryHallId");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("SmartFactoryCMMS.Api.Models.WorkOrder", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("AssignedUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("DueDate")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("MachineId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("ResolvedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TicketNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("AssignedUserId");

                    b.HasIndex("MachineId");

                    b.HasIndex("TicketNumber")
                        .IsUnique();

                    b.ToTable("WorkOrders");
                });

            modelBuilder.Entity("SmartFactoryCMMS.Api.Models.WorkShift", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<TimeSpan>("EndTime")
                        .HasColumnType("time");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<TimeSpan>("StartTime")
                        .HasColumnType("time");

                    b.HasKey("Id");

                    b.ToTable("WorkShifts");
                });

            modelBuilder.Entity("SmartFactoryCMMS.Api.Models.AlertThreshold", b =>
                {
                    b.HasOne("SmartFactoryCMMS.Api.Models.Machine", "Machine")
                        .WithMany("AlertThresholds")
                        .HasForeignKey("MachineId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Machine");
                });

            modelBuilder.Entity("SmartFactoryCMMS.Api.Models.Incident", b =>
                {
                    b.HasOne("SmartFactoryCMMS.Api.Models.Machine", "Machine")
                        .WithMany("Incidents")
                        .HasForeignKey("MachineId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Machine");
                });

            modelBuilder.Entity("SmartFactoryCMMS.Api.Models.Machine", b =>
                {
                    b.HasOne("SmartFactoryCMMS.Api.Models.FactoryHall", "FactoryHall")
                        .WithMany("Machines")
                        .HasForeignKey("FactoryHallId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SmartFactoryCMMS.Api.Models.ProductionLine", "ProductionLine")
                        .WithMany("Machines")
                        .HasForeignKey("ProductionLineId");

                    b.Navigation("FactoryHall");

                    b.Navigation("ProductionLine");
                });

            modelBuilder.Entity("SmartFactoryCMMS.Api.Models.MachinePrediction", b =>
                {
                    b.HasOne("SmartFactoryCMMS.Api.Models.Machine", "Machine")
                        .WithMany()
                        .HasForeignKey("MachineId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Machine");
                });

            modelBuilder.Entity("SmartFactoryCMMS.Api.Models.ProductionLine", b =>
                {
                    b.HasOne("SmartFactoryCMMS.Api.Models.Product", "CurrentProduct")
                        .WithMany("ProductionLines")
                        .HasForeignKey("CurrentProductId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("SmartFactoryCMMS.Api.Models.FactoryHall", "FactoryHall")
                        .WithMany("ProductionLines")
                        .HasForeignKey("FactoryHallId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CurrentProduct");

                    b.Navigation("FactoryHall");
                });

            modelBuilder.Entity("SmartFactoryCMMS.Api.Models.ProductionLog", b =>
                {
                    b.HasOne("SmartFactoryCMMS.Api.Models.Machine", "Machine")
                        .WithMany()
                        .HasForeignKey("MachineId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SmartFactoryCMMS.Api.Models.WorkShift", "Shift")
                        .WithMany("ProductionLogs")
                        .HasForeignKey("ShiftId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Machine");

                    b.Navigation("Shift");
                });

            modelBuilder.Entity("SmartFactoryCMMS.Api.Models.RefreshToken", b =>
                {
                    b.HasOne("SmartFactoryCMMS.Api.Models.User", "User")
                        .WithMany("RefreshTokens")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("SmartFactoryCMMS.Api.Models.TelemetryRead", b =>
                {
                    b.HasOne("SmartFactoryCMMS.Api.Models.Machine", "Machine")
                        .WithMany("TelemetryReads")
                        .HasForeignKey("MachineId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Machine");
                });

            modelBuilder.Entity("SmartFactoryCMMS.Api.Models.User", b =>
                {
                    b.HasOne("SmartFactoryCMMS.Api.Models.FactoryHall", "FactoryHall")
                        .WithMany("AssignedUsers")
                        .HasForeignKey("FactoryHallId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("FactoryHall");
                });

            modelBuilder.Entity("SmartFactoryCMMS.Api.Models.WorkOrder", b =>
                {
                    b.HasOne("SmartFactoryCMMS.Api.Models.User", "AssignedUser")
                        .WithMany("AssignedWorkOrders")
                        .HasForeignKey("AssignedUserId");

                    b.HasOne("SmartFactoryCMMS.Api.Models.Machine", "Machine")
                        .WithMany("WorkOrders")
                        .HasForeignKey("MachineId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AssignedUser");

                    b.Navigation("Machine");
                });

            modelBuilder.Entity("SmartFactoryCMMS.Api.Models.FactoryHall", b =>
                {
                    b.Navigation("AssignedUsers");

                    b.Navigation("Machines");

                    b.Navigation("ProductionLines");
                });

            modelBuilder.Entity("SmartFactoryCMMS.Api.Models.Machine", b =>
                {
                    b.Navigation("AlertThresholds");

                    b.Navigation("Incidents");

                    b.Navigation("TelemetryReads");

                    b.Navigation("WorkOrders");
                });

            modelBuilder.Entity("SmartFactoryCMMS.Api.Models.Product", b =>
                {
                    b.Navigation("ProductionLines");
                });

            modelBuilder.Entity("SmartFactoryCMMS.Api.Models.ProductionLine", b =>
                {
                    b.Navigation("Machines");
                });

            modelBuilder.Entity("SmartFactoryCMMS.Api.Models.User", b =>
                {
                    b.Navigation("AssignedWorkOrders");

                    b.Navigation("RefreshTokens");
                });

            modelBuilder.Entity("SmartFactoryCMMS.Api.Models.WorkShift", b =>
                {
                    b.Navigation("ProductionLogs");
                });
#pragma warning restore 612, 618
        }
    }
}
